version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: kitkatmukherjee2015@gmail.com
      GIT_NAME: bikram557
      VERSION: 2.2
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync golang-go
           git clone https://github.com/Bikram557/android_kernel_xiaomi_santoni_msm4.9 -b ten kernel
           cd kernel
           source ./unified.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
